export const WatchData=[
    {
        id: 1,
        name: "Apple Watch Series 9",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-compare-series9-202309?wid=198&hei=234&fmt=jpeg&qlt=95&.v=1692836321777",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹41900.00",
    },
    {
        id: 2,
        name: "Apple Watch Ultra 2",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-compare-ultra-202309_GEO_IN?wid=222&hei=256&fmt=jpeg&qlt=95&.v=1693530410569",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹89900.00",
    },
    {
        id: 3,
        name: "Apple Watch SE",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-compare-se-202309?wid=198&hei=234&fmt=jpeg&qlt=95&.v=1692837324943",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹28900.00",
    },
    {
        id: 4,
        name: "Apple Watch SE-2",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-se-digitalmat-gallery-1-202309?wid=364&hei=333&fmt=png-alpha&.v=1693271766625",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹32000.00",
    },
    {
        id: 5,
        name: "Apple Watch Ultra",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-ultra2-digitalmat-gallery-1-202309_GEO_IN?wid=364&hei=333&fmt=jpeg&qlt=95&.v=1693846567708",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹80900.00",
    },
    {
        id: 6,
        name: "Apple Watch 6",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-s9-digitalmat-gallery-3-202309_GEO_IN?wid=364&hei=333&fmt=png-alpha&.v=1693846443116",
        desc:"All Apple Watch Series 9 cases are swimproof and dustproof, and have crack-resistant front crystals.",
        title:"45mm or 41mm aluminium or stainless steel case",
        price:"From ₹28900.00",
    },
];