export const  IphoneData = [
    {
        id: 1,
        name: "iPhone 15 Pro",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-compare-iphone-15-pro-202309?wid=384&hei=512&fmt=jpeg&qlt=90&.v=1692827834790",
        desc:"17.00 cm (6.7″) or 15.54 cm (6.1″) Super Retina XDR display footnote ProMotion technology Always-On display",
        title:"The ultimate iPhone.For when things just pop up.",
        price:"134900.00",
        amount: 1,
    },
    {
        id: 2,
        name: "iPhone 15",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-compare-iphone-15-202309?wid=384&hei=512&fmt=jpeg&qlt=90&.v=1692827832423",
        desc:"Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can track your next ride, see who’s calling, check your flight status and so much more.",
        title:"Dynamic Island.For when things just pop up.",
        price:"79900.00",
        amount: 1,
    },
    {
        id: 3,
        name: "iPhone 14",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-compare-iphone-14-202309?wid=384&hei=512&fmt=jpeg&qlt=90&.v=1693516153040",
        desc:"The iPhone 14 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 15.40 centimetres (6.06″) diagonally (actual viewable area is less).",
        title:"Ceramic Shield front Glass back and aluminium design",
        amount: 1,
        price:"10983.00",
    },
    {
        id: 4,
        name: "iPhone 14 plus",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-compare-iphone-14-202309?wid=384&hei=512&fmt=jpeg&qlt=90&.v=1693516153040",
        desc:"The iPhone 14 Plus display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 16.95 centimetres (6.68″) diagonally (actual viewable area is less).",
        title:"Ceramic Shield front Glass back and aluminium design",
        amount: 1,
        price:"12983.00",
    },
    {
        id: 5,
        name: "iPhone 13",
        image: "https://pngimg.com/uploads/iphone_14/iphone_14_PNG41.png",
        desc:"The iPhone 13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 16.95 centimetres (6.68″) diagonally (actual viewable area is less).",
        title:"Ceramic Shield front Glass back and aluminium design",
        price:"80900.00",
        amount: 1,
    },
    {
        id: 6,
        name: "iPhone 13 Pro",
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-compare-iphone-15-pro-202309?wid=384&hei=512&fmt=jpeg&qlt=90&.v=1692827834790",
        desc:"The iPhone 13 Pro display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 16.95 centimetres (6.68″) diagonally (actual viewable area is less).",
        title:"Ceramic Shield front Glass back and aluminium design",
        amount: 1,
        price:"12900.00",
    },

];